/*
 * This Spock specification was generated by the Gradle 'init' task.
 */

import circular.generics.Library
import spock.lang.Specification

class LibraryTest extends Specification {

    def "someLibraryMethod returns true"() {
        setup:
        def lib = new Library()

        when:
        def result = lib.findOrCreateTheProblematicClass('cat1')

        then:
        result
    }

}
