/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package circular.generics

import generics.GenericConsumer

class Library {

    GenericConsumer findOrCreateTheProblematicClass(String aCategory) {
        // The compiler crashes with StackoverflowError when entering the closure, because it can't resolve the generic parameter in AllAtOnce
        GenericConsumer problemClass = anotherTestMethod { ->
            (GenericConsumer.findSpecificType(aCategory) as GenericConsumer).testMethod()
        } as GenericConsumer

        return problemClass
    }

    static <T> T anotherTestMethod(Closure<T> statement) {
        def result
        try {
            result = statement()
        } catch (Exception e) {
            result = statement()
        }
        return result
    }

}
